artikel/urls.py
from django.urls import path
from . import views

app_name = 'artikel'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('awareness/', views.awareness_list, name='awareness_list'),
    path('awareness/<int:year>/<int:month>/<int:day>/<slug:awareness>/', views.awareness_detail, name='awareness_detail'),
    path('<slug:type_slug>/', views.product_list, name='product_list_by_type'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]

hope/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "HOPE PROJECT" # modify Admin Site Header
admin.site.site_title = "HOPE PROJECT" # modify Admin Site Title
admin.site.index_title = "Admin" # modify Admin Index Title

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('artikel/', include('artikel.urls')),
    path('artikel/', include('artikel.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# tambahkan gambar
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artikel/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import mark_safe # menampilkan gambar di admin
import uuid # untuk generate id
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField # untuk ckeditor


#=====================================================================
class Size(models.Model):
    size_name = models.CharField(max_length=5)

    class Meta:
        ordering = ['size_name']
        verbose_name = 'Size'
        verbose_name_plural = 'Size'

    def __str__(self):
        return self.size_name

#=====================================================================
class Type(models.Model):
    type_name = models.CharField(max_length=20, db_index=True)
    slug = models.SlugField(max_length=20, unique=True, null=False, db_index=True)

    class Meta:
        ordering = ['type_name']
        verbose_name = 'Type'
        verbose_name_plural = 'Type'

    def __str__(self):
        return self.type_name

    def get_absolute_url(self):
        return reverse('artikel:product_list_by_type', args=[self.slug])


#=====================================================================
class Product(models.Model):
    name = models.CharField(max_length=20, db_index=True)
    slug = models.SlugField(max_length=20, unique=True, null=False, db_index=True)
    description = models.TextField(max_length=100, help_text='(max = 100 character)')
    figure1 = models.ImageField(upload_to='products', null=True, blank=True)
    figure2 = models.ImageField(upload_to='products', null=True, blank=True)
    size = models.ManyToManyField(Size)
    type = models.ForeignKey('Type', on_delete=models.SET_NULL, null=True, related_name='products',)
    available = models.BooleanField(default=True)
    price = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(default=timezone.now)

    # tampilkan gambar di admin:
    @property
    def figure1_preview(self):
        if self.figure1:
            return mark_safe('<img src="{}" width="auto" height="100" />'.format(self.figure1.url))
        return ''

    @property
    def figure2_preview(self):
        if self.figure2:
            return mark_safe('<img src="{}" width="auto" height="100" />'.format(self.figure2.url))
        return ''

    class Meta:
        ordering = ['created']
        index_together = (('id', 'slug'),)
        verbose_name = 'Name'
        verbose_name_plural = 'Name'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('artikel:product_detail',
        args=[self.id, self.slug])

    # tambahan method untuk ManyToManyField = size
    def product_size(self):
        return ', '.join(size.size_name for size in self.size.all()[:5])

    product_size.short_description = 'Size'

#=====================================================================
class StockLog(models.Model):
    id = models.UUIDField('Code', primary_key=True, default=uuid.uuid4)
    product = models.ForeignKey('Product', verbose_name='Name', on_delete=models.SET_NULL, null=True)
    production_date = models.DateField(null=True, blank=True)
    quantity = models.IntegerField(default=0)

    sold = models.IntegerField(default=0)

    class Meta:
        ordering = ['production_date', 'product', 'quantity', 'sold']
        verbose_name = 'Stock Log'
        verbose_name_plural = 'Stock Log'

    def __str__(self):
        return f'{self.product.name} ({self.id})'

    # method untuk mengambil value dari CLASS LAIN (product) --> tapi harus ForeignKey dari class ini
    def price(self):
        return self.product.price if self.product else None

    # method untuk mendapatkan sisa produk:
    def remaining(self):
        return self.quantity - self.sold

    # method untuk mendapatkan revenue:
    def revenue(self):
        return self.quantity * self.price()

#=====================================================================
#class PublishedManager(models.Manager):
#    def get_queryset(self):
#        return super(PublishedManager, self).get_queryset().filter(status='published')

class Awareness(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=50, unique=True, null=False, db_index=True)
    body = RichTextUploadingField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES,
                            default='draft')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-updated',)

    objects = models.Manager() 
#    published = PublishedManager()   # Our custom manager.

    def get_absolute_url(self):
        return reverse('artikel:awareness_detail',
                        args = [self.updated.year,
                                self.updated.month,
                                self.updated.day,
                                self.slug])

artikel/views.py
from django.shortcuts import render, get_object_or_404
from artikel.models import Product, Size, Type, StockLog, Awareness


# Ini cuma Test aja...   ================================
from django.http import HttpResponse
def test(request):
    text = """<h1>Tes Saja!</h1>"""
    return HttpResponse(text)

# PRODUCT ===============================================
def product_list(request, type_slug=None):
    type = None
    types = Type.objects.all()
    products = Product.objects.filter(available=True)
    if type_slug:
        type = get_object_or_404(Type, slug=type_slug)
        products = products.filter(type=type)
    return render(request,
                    'artikel/product/list.html',
                    {'type': type,
                    'types': types,
                    'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                    'artikel/product/detail.html',
                    {'product': product})

# AWARENESS ===============================================

def awareness_list(request):
    awarenesses = Awareness.objects.all()
    return render(request,
                    'artikel/awareness/list.html',
                    {'awarenesses': awarenesses}
                    )

def awareness_detail(request, year, month, day, awareness):
    awareness = get_object_or_404(Awareness, slug=awareness,
                                    status='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)
    return render(request,
                    'artikel/product/detail.html',
                    {'awareness': awareness})

artikel/templates/artikel/awareness/list.html
{% extends "base.html" %}

{% block title %}
	Awareness
{% endblock %}

{% block content %}
  <h1>Awareness</h1>

  {% for apapun in awarenesses %} <!-- ambil attribute dari fungsi di views = awarenesses -->
    <h2>
      <a href="{{ apapun.get_absolute_url }}">{{ apapun.title }}</a>
    </h2>
    <p>Published {{ apapun.updated }}</p>
    <p>{{ apapun.body|safe|truncatewords:15|linebreaks }}</p>
		<!-- tambah |safe untuk data yang ditarik dari ckeditor -->
  {% endfor %}

{% endblock %}

artikel/templates/artikel/product/detail.html
{% extends "base.html" %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div>
    <img src="{% if product.figure1 %}{{ product.figure1.url }}{% endif %}">
      {% if product.figure2 %}<img src="{{ product.figure2.url }}">{% endif %}
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.type.get_absolute_url }}">{{ product.type }}</a></h2>
    <p>${{ product.price }}</p>
      {{ product.description|linebreaks }}
  </div>
{% endblock %}

artikel/templates/artikel/product/list.html
{% extends "base.html" %}

{% block title %}
	{% if type %}
		{{ type.type_name }}
	{% else %}Galleries
	{% endif %}
{% endblock %}


{% block content %}

			<header>
				<ul class="tabs">
						<li {% if not type %}class="button"{% endif %}>
							<a href="{% url 'artikel:product_list' %}" class="button">All</a>
						</li>
						{% for c in types %}
							<li {% if type.slug == c.slug %}class="button"{% endif %}>
								<a href="{{ c.get_absolute_url }}" class="button">{{ c.type_name }}</a>
							</li>
						{% endfor %}
				</ul>
			</header>

			<div>
				<h1>
					{% if type %}
						{{ type.type_name }}
					{% else %}Galleries
					{% endif %}
				</h1><hr>
			</div>

			<div class="content">
				{% for product in products %}
								<div class="media">
									<a href="{{ product.get_absolute_url }}">
										<img src="{{ product.figure1.url }}">
									</a>
									<p><a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
									Rp {{ product.price }}</p>
								</div>

				{% endfor %}
			</div>

{% endblock %}

artikel/templates/base.html
<!DOCTYPE HTML>
<html lang=en>

<head>
	<title>HOPE | {% block title %}{% endblock %}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	{% load static %}
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	{% load icons %}
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
	  integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
	<div class="page-wrap">

		<nav id="nav">
			<ul>
				<li><a href="{% url 'artikel:product_list' %}"><span class="icon fa-home"></span></a></li>
				<li><a href="{% url 'artikel:awareness_list' %}"><span class="icon far fa-newspaper-o"></span></a></li>
				<li><a href="#contact"><span class="icon fa-address-book"></span></a></li>
			</ul>
		</nav>

		<section id="main">
			<section id="gallery" class="gallery">
				{% block content %}
				{% endblock %}
			</section>
			<section id="contact">
				<div class="social column">
					<h3>About Us</h3>
					<p>Mus sed interdum nunc dictum rutrum scelerisque erat a parturient condimentum potenti dapibus vestibulum condimentum per tristique porta. Torquent a ut consectetur a vel ullamcorper a commodo a mattis ipsum class quam sed eros vestibulum quisque a eu nulla scelerisque a elementum vestibulum.</p>
					<p>Aliquet dolor ultricies sem rhoncus dolor ullamcorper pharetra dis condimentum ullamcorper rutrum vehicula id nisi vel aptent orci litora hendrerit penatibus erat ad sit. In a semper velit eleifend a viverra adipiscing a phasellus urna praesent parturient integer ultrices montes parturient suscipit posuere quis aenean. Parturient euismod ultricies commodo arcu elementum suspendisse id dictumst at ut vestibulum conubia quisque a himenaeos dictum proin dis purus integer mollis parturient eros scelerisque dis libero parturient magnis.</p>
					<h3>Follow Us</h3>
					<ul class="icons">

<!--					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>    -->
							<li><a href="https://www.facebook.com/kansil.dika.7" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
							<li><a href="https://www.instagram.com/hopeproject.jkt/" class="icon fa-instagram"><span class="label">Instagram</span></a></li>

					</ul>
				</div>
				<div class="column">
					<h3>Get in Touch</h3>
					<form action="#" method="post">
						<div class="field half first">
							<label for="name">Name</label>
							<input name="name" id="name" type="text" placeholder="Name">
						</div>
						<div class="field half">
							<label for="email">Email</label>
							<input name="email" id="email" type="email" placeholder="Email">
						</div>
						<div class="field">
							<label for="message">Message</label>
							<textarea name="message" id="message" rows="6" placeholder="Message"></textarea>
						</div>
						<ul class="actions">
							<li><input value="Send Message" class="button" type="submit"></li>
						</ul>
					</form>
				</div>
			</section>
			<footer id="footer">
				<div class="copyright">
<!--			&copy; Untitled Design: <a href="https://templated.co/">TEMPLATED</a>.  -->
				</div>
			</footer>
		</section>

	</div>
</body>
</html>